name: Python tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "requirements.txt" 
      - ".github/workflows/*.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "requirements.txt" 
      - ".github/workflows/*.yml"
jobs:
  test:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        torch: [{base: '2.5.1', vision: '0.20.1'}]
        python: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .